In [3]:
import numpy as np

In [5]:
a1=[[1,1,1],[2,2,2],[3,3,3]]
a2=[1,2,3]
b1=np.array(a1)
b2=np.array(a2)

In [9]:
#Numpy 모듈 제공 함수
print(b1)
print(b1.sum())
print(np.sum(b1))
print(b1.sum(axis=0))

[[1 1 1]
 [2 2 2]
 [3 3 3]]
18
18
[6 6 6]


In [15]:
#mean, sqrt, max, min, log
print(b1.mean())
print(np.sqrt(4))
print(np.max([1,2,3]))
print(np.log(10))

2.0
2.0
3
2.302585092994046


In [17]:
#정렬
a=[[4,3,5],[2,5,1],[7,6,9]]
arr1=np.array(a)

In [19]:
print(np.sort(arr1))                #default 행기준
print(np.sort(arr1, axis=1))    #행기준 정렬
print(np.sort(arr1, axis=0))    #열기준 정렬
print(np.sort(arr1, axis=0)[::-1,::])   #열기준 역순 정렬
print(np.sort(arr1, axis=0)[::,::-1])   #행기준 역순 정렬

[[3 4 5]
 [1 2 5]
 [6 7 9]]
[[3 4 5]
 [1 2 5]
 [6 7 9]]
[[2 3 1]
 [4 5 5]
 [7 6 9]]
[[7 6 9]
 [4 5 5]
 [2 3 1]]
[[1 3 2]
 [5 5 4]
 [9 6 7]]


In [21]:
print(arr1)
print(arr1.transpose())     #전치행렬

[[4 3 5]
 [2 5 1]
 [7 6 9]]
[[4 2 7]
 [3 5 6]
 [5 1 9]]


In [24]:
print(arr1>=5)      #논리연산
print(np.all(arr1>3))         #모든 요소가 3보다 클 경우 true
print(np.any(arr1>3))       #하나의 요소만 3보다 클 경우 true

[[False False  True]
 [False  True False]
 [ True  True  True]]
False
True


In [27]:
#0,1으로 셋팅하여 생성
a=np.zeros(10)
a2=np.zeros([3,3])
print(a1)
print(a2)
a=np.ones(10)
a2=np.ones([3,3])
print(a1)
print(a2)

[[1, 1, 1], [2, 2, 2], [3, 3, 3]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1, 1, 1], [2, 2, 2], [3, 3, 3]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [29]:
print(arr1)
b1=np.ones_like(arr1)
b2=np.zeros_like(arr1)
print(b1)
print(b2)

[[4 3 5]
 [2 5 1]
 [7 6 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
#https://grouplens.org/datasets/movielens/
#old dataSets - ml-1m.zip 다운로드