In [4]:
import numpy as np

In [5]:
a=[1,2,3,4,5]
b=np.array(a)
print(a, type(a))
print(b, type(b))

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>


In [7]:
b=np.arange(1,10,2)
print(b, type(b), b.shape)

[1 3 5 7 9] <class 'numpy.ndarray'> (5,)


In [9]:
a=[[1,2,3],[4,5,6]]
b=np.array(a)
print(b, b.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


In [11]:
a=[1,2,3,4,5,6]
b=np.array(a).reshape(2,3)
c=np.array(a).reshape(3,2)
print(b)
print(c)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [20]:
print(b[0])
print(b[1][1])
print(b[:,1:])

[1 2 3]
5
[[2 3]
 [5 6]]


In [21]:
a=[[1,2,3],[4,5,6]]
print(a[:][0])

[1, 2, 3]


In [23]:
print(a)
print(b)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


In [27]:
print(a*2)
print(b*2)

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]
[[ 2  4  6]
 [ 8 10 12]]


In [31]:
aa=[1,2,3,4]
bb=[7,8]
arr1=np.array(aa)
arr2=np.array(bb)
print(aa+bb)
print(arr1+3)
print(arr1-1)
print(arr1*2)
print(arr1/2)
print(arr1//2)
print(arr1%2)

[1, 2, 3, 4, 7, 8]
[4 5 6 7]
[0 1 2 3]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[0 1 1 2]
[1 0 1 0]


In [33]:
a1=[[1,1,1],[2,2,2],[3,3,3]]
a2=[1,2,3]
b1=np.array(a1)
b2=np.array(a2)
print(b1)
print(b2)
print(b1+b2)
#행렬 연산 지원
#크기가 다른 두 행렬의 연산 지원

[[1 1 1]
 [2 2 2]
 [3 3 3]]
[1 2 3]
[[2 3 4]
 [3 4 5]
 [4 5 6]]
